### ISSUE TITLE
Minimum builderFeatures required; persistent output flag error

### ISSUE THREAD

**Issue by CarlosV89** [ember-cli/broccoli-lint-eslint#39]
Howdy! Im trying to use the ember-cli-eslint module that uses broccoli-lint-eslint, its throwing that error when I try to build or test and if we add the persistent output flag to true here
https://github.com/ember-cli/broccoli-lint-eslint/blob/master/lib/index.js#L66

It seems to fix it for us. Do you have any idea what could be causing this or how we could fix it? Or any information as to what IS the persistent output flag

**Comment by rwjblue** [comment]
Can you provide a demo/example that shows the error? I'm not sure how to reproduce....

**Comment by CarlosV89** [comment]
I'm not sure how to reproduce it myself either, I just did `ember install ember-cli-eslint`... 
here's where we add the flag, it was in a `index.js`
```
// eslint-disable-next-line no-underscore-dangle
  var nodeInfo = inputNode.__broccoliGetInfo__({
    persistentOutputFlag: true,
    sourceDirectories: true
  });

**Comment by ivanvotti** [comment]
I got the same error:

```
$ ember test
⠋ BuildingMinimum builderFeatures required: { persistentOutputFlag: true }
Error: Minimum builderFeatures required: { persistentOutputFlag: true }
    at Funnel.Plugin._checkBuilderFeatures (/myproject/node_modules/broccoli-plugin/index.js:62:11)
    at Funnel.Plugin.__broccoliGetInfo__ (/myproject/node_modules/broccoli-plugin/index.js:45:8)
    at resolveInputDirectory (/myproject/node_modules/broccoli-lint-eslint/build/index.js:69:28)
    at new EslintValidationFilter (/myproject/node_modules/broccoli-lint-eslint/build/index.js:120:19)
    at EslintValidationFilter (/myproject/node_modules/broccoli-lint-eslint/build/index.js:91:12)
    at CoreObject.module.exports.lintTree (/myproject/node_modules/ember-cli-eslint/index.js:30:12)
    at /myproject/node_modules/ember-cli/lib/broccoli/ember-app.js:574:20
    at Array.map (native)
    at EmberAddon.EmberApp.addonLintTree (/myproject/node_modules/ember-cli/lib/broccoli/ember-app.js:572:36)
    at EmberAddon.EmberApp.appTests (/myproject/node_modules/ember-cli/lib/broccoli/ember-app.js:1088:26)
    at EmberAddon.EmberApp.test (/myproject/node_modules/ember-cli/lib/broccoli/ember-app.js:1074:26)
    at EmberAddon.EmberApp.toArray (/myproject/node_modules/ember-cli/lib/broccoli/ember-app.js:1573:61)
    at EmberAddon.EmberApp.toTree (/myproject/node_modules/ember-cli/lib/broccoli/ember-app.js:1588:30)
    at module.exports (/myproject/ember-cli-build.js:13:14)
    at CoreObject.module.exports.Task.extend.setupBroccoliBuilder (/myproject/node_modules/ember-cli/lib/models/builder.js:54:19)
    at CoreObject.module.exports.Task.extend.init (/myproject/node_modules/ember-cli/lib/models/builder.js:89:10)
    at CoreObject.superWrapper [as init] (/myproject/node_modules/core-object/lib/assign-properties.js:32:18)
    at CoreObject.Class (/myproject/node_modules/core-object/core-object.js:32:33)
    at CoreObject.module.exports.Task.extend.run (/myproject/node_modules/ember-cli/lib/tasks/build.js:15:19)
    at CoreObject.<anonymous> (/myproject/node_modules/ember-cli/lib/commands/test.js:164:27)
    at lib$rsvp$$internal$$tryCatch (/myproject/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/myproject/node_modules/rsvp/dist/rsvp.js:1048:17)
```

**Comment by ivanvotti** [comment]
I can't reproduce the error anymore. I'm not sure what exactly fixed it, I just did two things:
- downgraded `npm` from 3.10.6 to 2.15.9
- upgraded my addon's broccoli-caching-writer from 2.2.1 to 2.3.1

**Comment by plicjo** [comment]
I fixed this by removing the `ember-cli-sri` package.

**Comment by csprocket777** [comment]
What was the solution here? I'm running into this same error when trying run `ember test` on my code. 

I'm using a gitlab-ci runner in specific branches to run test and build my code, in the develop branch it's running fine. In my stage branch it reports this error.

Just tried removing `ember-cli-sri` and still receive the same error.

**Comment by rwjblue** [comment]
I unpublished broccoli-builder 0.18.12 a few minutes ago, which should resolve the issue for folks...

**Comment by csprocket777** [comment]
Still no luck for me.

Here's what I did:
- `rm -rf node_modules/ tmp/`
- `npm cache clean`
- `npm install`
- `ember test`

This is what I get from the log:
```
=================================================================================

ENV Summary:

  TIME: Tue May 22 2018 23:17:14 GMT+0000 (UTC)
  TITLE: ember
  ARGV:
  - /home/gitlab-runner/.nvm/versions/node/v7.2.0/bin/node
  - /home/gitlab-runner/.nvm/versions/node/v7.2.0/bin/ember
  - test
  EXEC_PATH: /home/gitlab-runner/.nvm/versions/node/v7.2.0/bin/node
  TMPDIR: /tmp
  SHELL: /bin/bash
  PATH:
  - /home/gitlab-runner/.nvm/versions/node/v7.2.0/bin
  - /sbin
  - /bin
  - /usr/sbin
  - /usr/bin
  - /usr/local/bin/
  PLATFORM: linux x64
  FREEMEM: 1595400192
  TOTALMEM: 8371421184
  UPTIME: 697079
  LOADAVG: 1.13623046875,1.07958984375,0.86669921875
  CPUS:
  - Intel Xeon E3-12xx v2 (Ivy Bridge) - 2799
  - Intel Xeon E3-12xx v2 (Ivy Bridge) - 2799
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.10.1-DEV
  - cldr: 30.0.2
  - http_parser: 2.7.0
  - icu: 58.1
  - modules: 51
  - node: 7.2.0
  - openssl: 1.0.2j
  - tz: 2016g
  - unicode: 9.0
  - uv: 1.10.1
  - v8: 5.4.500.43
  - zlib: 1.2.8

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Minimum builderFeatures required: { persistentOutputFlag: true }
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Minimum builderFeatures required: { persistentOutputFlag: true }
  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: Error: Minimum builderFeatures required: { persistentOutputFlag: true }
    at SRIHashAssets.Plugin._checkBuilderFeatures (/home/gitlab-runner/builds/12157f87/0/digitalization/personal_network_visualization/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/index.js:62:11)
    at SRIHashAssets.Plugin.__broccoliGetInfo__ (/home/gitlab-runner/builds/12157f87/0/digitalization/personal_network_visualization/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/index.js:45:8)
    at getPluginName (/home/gitlab-runner/builds/12157f87/0/digitalization/personal_network_visualization/node_modules/broccoli-builder/lib/builder.js:291:23)
    at new Node (/home/gitlab-runner/builds/12157f87/0/digitalization/personal_network_visualization/node_modules/broccoli-builder/lib/builder.js:260:11)
    at readAndReturnNodeFor (/home/gitlab-runner/builds/12157f87/0/digitalization/personal_network_visualization/node_modules/broccoli-builder/lib/builder.js:112:16)
    at /home/gitlab-runner/builds/12157f87/0/digitalization/personal_network_visualization/node_modules/broccoli-builder/lib/builder.js:52:14
    at tryCatch (/home/gitlab-runner/builds/12157f87/0/digitalization/personal_network_visualization/node_modules/broccoli-builder/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/home/gitlab-runner/builds/12157f87/0/digitalization/personal_network_visualization/node_modules/broccoli-builder/node_modules/rsvp/dist/rsvp.js:538:13)
    at /home/gitlab-runner/builds/12157f87/0/digitalization/personal_network_visualization/node_modules/broccoli-builder/node_modules/rsvp/dist/rsvp.js:606:14
    at flush (/home/gitlab-runner/builds/12157f87/0/digitalization/personal_network_visualization/node_modules/broccoli-builder/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by SaraaraS** [comment]
NPM is still showing 0.18.12, any ideas how long the unpublish version should take? Thanks!

**Comment by rwjblue** [comment]
Hmph. I would have expected it to be nearly instant.

**Comment by andyhot** [comment]
Must be some caching involved - with yarn you should be able to lookup broccoli-builder in yarn.lock and make sure it reads
```
broccoli-builder@^0.18.8:
  version "0.18.11"
  resolved "https://registry.yarnpkg.com/broccoli-builder/-/broccoli-builder-0.18.11.tgz#a42393c7b10bb0380df255a616307945f5e26efb"
  dependencies:
    heimdalljs "^0.2.0"
    promise-map-series "^0.2.1"
    quick-temp "^0.1.2"
    rimraf "^2.2.8"
    rsvp "^3.0.17"
    silent-error "^1.0.1"
```
and then `yarn install --pure-lockfile`

**Comment by Turbo87** [comment]
@rwjblue npm had issues with deploys not showing up and stuff like that, maybe unpublish was also affected 🤔

**Comment by rwjblue** [comment]
Just in case, I just revertted the affecting PR (https://github.com/ember-cli/broccoli-builder/pull/28) and published broccoli-builder@0.18.13.

**Comment by IAmJulianAcosta** [comment]
I confirm that @rwjblue fix works :)

**Comment by csprocket777** [comment]
Yup. works for me. Thank you! @rwjblue **ROCKS**
